project_id = "wnedqmxejgynelhtbpmw"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "https://eec7ddf3-9540-4766-8910-2c4d69b9943a.lovableproject.com"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
refresh_token_reuse_interval = 10
enable_signup = true
enable_anonymous_sign_ins = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[auth.sms]
enable_signup = false
enable_confirmations = false
template = "Your code is {{ .Code }} ."

[functions.check-overdue-invoices]
verify_jwt = false

[functions.delete-customer]
verify_jwt = false

[functions.send-registration-notification]
verify_jwt = false

[functions.approve-tenant]
verify_jwt = false

[functions.send-contact-email]
verify_jwt = false

[functions.send-invoice-email]
verify_jwt = false

[functions.reset-customer-password]
verify_jwt = false

[functions.check-user-exists]
verify_jwt = false