version: '3.8'

services:
  # Main application
  cozy-invoice:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
      - VITE_APP_URL=${VITE_APP_URL:-http://localhost:3000}
    volumes:
      - ./public:/usr/share/nginx/html/public:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - cozy-network

  # Optional: Supabase local development (uncomment if needed)
  # supabase:
  #   image: supabase/postgres:15.1.0.117
  #   environment:
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-your-super-secret-password}
  #     POSTGRES_DB: ${POSTGRES_DB:-postgres}
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - supabase_db_data:/var/lib/postgresql/data
  #   networks:
  #     - cozy-network

  # Optional: Redis for caching (uncomment if needed)
  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data
  #   networks:
  #     - cozy-network

networks:
  cozy-network:
    driver: bridge

volumes:
  supabase_db_data:
  redis_data:
